### ISSUE TITLE
Exception when trying to start the website in IIS

### ISSUE THREAD

**Issue by JVanloofsvelt** [antoinemartin/django-windows-tools#26]
I'm using Django 1.9.13

```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\python27\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\python27\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\python27\Lib\site-packages\wfastcgi.py", line 605, in get_wsgi_handler
    handler = handler()
  File ".\ptvs_virtualenv_proxy.py", line 102, in get_virtualenv_handler
    handler = get_wsgi_handler(os.getenv('WSGI_ALT_VIRTUALENV_HANDLER'))
  File ".\ptvs_virtualenv_proxy.py", line 76, in get_wsgi_handler
    handler = getattr(handler, name)
AttributeError: 'module' object has no attribute 
```

I've been looking for the cause, but couldn't find it yet

I am using a project structure where the settings and root urls.py still reside in a subfolder (Django 1.6 application that I just upgraded to Django 1.9). I have moved the wsgi.py from this subfolder up one level, thinking that might help ...

**Comment by mrbean-bremen** [comment]
From the call stack it looks like you are using wfastcgi, and the problem appears there. I have no experience with that, and I don't know how it plays with django-windows-tools. Could you give some more information about your setup, specifically how django-windows-tools is involved?
