### ISSUE TITLE
python manage.py help winfcgi_install fails with an exception

### ISSUE THREAD

**Issue by beruic** [antoinemartin/django-windows-tools#29]
The exception is the following: 

```
(my-service) C:\sites\my-service>python manage.py help winfcgi_install
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\venv\my-service\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\venv\my-service\lib\site-packages\django\core\management\__init__.py", line 348, in execute
    self.fetch_command(options.args[0]).print_help(self.prog_name, options.args[0])
  File "C:\venv\my-service\lib\site-packages\django\core\management\base.py", line 264, in print_help
    parser.print_help()
  File "c:\python36\Lib\argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "c:\python36\Lib\argparse.py", line 2350, in format_help
    return formatter.format_help()
  File "c:\python36\Lib\argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "c:\python36\Lib\argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "c:\python36\Lib\argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "c:\python36\Lib\argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "c:\python36\Lib\argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "c:\python36\Lib\argparse.py", line 523, in _format_action
    help_text = self._expand_help(action)
  File "c:\python36\Lib\argparse.py", line 610, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character 'S' (0x53) at index 41
```

**Comment by mrbean-bremen** [comment]
Have you added django_windows_tools to your installed apps? E.g. in `settings.py`:
```python
INSTALLED_APPS += (
        'django_windows_tools',
    )
```

**Comment by beruic** [comment]
Yes I have. Mine is a list though, instead of a tuple.

**Comment by mrbean-bremen** [comment]
Closing stale issue in unmaintained project.
